name: ajaaja_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.1
  collection: ^1.17.1
  connectivity_plus: ^4.0.1
  dio: ^5.2.1+1
  dynamic_color: ^1.6.5
  equatable: ^2.0.5
  firebase_analytics: ^10.4.3
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.3
  firebase_storage: ^11.2.3
  flutter:
    sdk: flutter
  flutter_flavorizr: ^2.2.1
  flutter_local_notifications: ^14.1.1
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.4.0
  go_router: ^9.0.0
  flutter_native_splash: ^2.3.1

  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^1.4.0
  path: ^1.8.3
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  shared_preferences: ^2.2.0


dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  custom_lint: null
  riverpod_lint: null
  flutter_test:
    sdk: flutter

  go_router_builder: ^2.1.1
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.1

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/data/

flutter_native_splash:
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
  ios_content_mode: center

