name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release lib/main_prod.dart --web-renderer=auto --base-href /aja-aja-app/
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          targetBranch: gh-pages
          baseHref: /aja-aja-app
